---
ansible_user: ubuntu

alloy_config: "{{ lookup('file', 'grafana/mimir.alloy') }}"

# Blocks storage requires a prefix when using a common object storage bucket.
mimir_blocks_storage:
  storage_prefix: blocks
  tsdb:
    dir: "{{ mimir_working_path}}/ingester"

# A gossip-based protocol uses memberlist to enable the 3 Mimir replicas to communicate
mimir_memberlist:
  join_members: "{{ groups['mimir'] | sort }}"
    # - dogchow1
    # - dogchow2
    # - dogchow3
