---
ansible_user: root
bind9_servers_zone_default_ttl: 90

bind9_servers_zones:
  - name: "lab.{{ showcase_base_domain }}"
    primaries:
      - "192.168.6.11"

  - name: '6.168.192.in-addr.arpa'
    primaries:
      - "192.168.6.11"
