---
# Showcases how a name server can be configured as a
# Secondary that has different Primary name servers
# for the zones.
# Also, how to configure a zone to be forwarded to specific
# name servers. This may be required in a private network
# with an internal domain name that does not exist on the
# public Internet.

bind9_servers_zones:
  - name: "lab.{{ showcase_base_domain }}"
    primaries:
      - "192.168.6.14"

  - name: forwarded.zone.example.com
    forwarders:
      - "8.8.8.8"
      - "8.8.4.4"

  - name: '6.168.192.in-addr.arpa'
    primaries:
      - "192.168.6.15"
