---
- name: Acquire various files from URLs.
  gather_facts: false
  hosts: localhost

  tasks:
    - name: Create the files directory.
      ansible.builtin.file:
        path: files
        state: directory
        mode: "0755"

    - name: Download cloud-init image files.
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "files/{{ item.dest | default(item.url | basename) }}"
      loop_control:
        label: "{{ item.name }}"
      loop:
        - name: Debian 12 generic
          url: https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-amd64.qcow2
        - name: Debian 13 generic
          url: https://cloud.debian.org/images/cloud/trixie/latest/debian-13-genericcloud-amd64.qcow2
        - name: Ubuntu 22.04 (jammy)
          url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
          dest: ubuntu-22.04-server.qcow2
        - name: Ubuntu 24.04 (noble)
          url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
          dest: ubuntu-24.04-server.qcow2
        - name: Ubuntu 26.04 (resolute)
          url: https://cloud-images.ubuntu.com/resolute/current/resolute-server-cloudimg-amd64.img
          dest: ubuntu-26.04-server.qcow2

    - name: Download CT templage files.
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "files/{{ item.dest | default(item.url | basename) }}"
      loop_control:
        label: "{{ item.name }}"
      loop:
        - name: Debian 12 standard template
          url: http://download.proxmox.com/images/system/debian-12-standard_12.12-1_amd64.tar.zst
        - name: Debian 13 standard template
          url: http://download.proxmox.com/images/system/debian-13-standard_13.1-2_amd64.tar.zst
        - name: Ubuntu 24.04 standard template
          url: http://download.proxmox.com/images/system/ubuntu-24.04-standard_24.04-2_amd64.tar.zst
        - name: Ubuntu 26.04 standard template
          url: http://download.proxmox.com/images/system/ubuntu-26.04-standard_26.04-1_amd64.tar.zst
