---
- name: Create builder CT.
  gather_facts: false
  hosts: local_builder

  roles:
    - name: cloudcodger.proxmox_client.lxc
    - name: cloudcodger.proxmox_client.add_guest_host

- name: Update cloud init image files.
  hosts: builder

  roles:
    - name: cloudcodger.ubuntu.initial_apt_update

  tasks:
    - name: Install libguestfs-tools package.
      ansible.builtin.apt:
        name: libguestfs-tools
        cache_valid_time: 3600
        state: present

    - name: Download cloud-init image file.
      ansible.builtin.get_url:
        url: "{{ item.src }}"
        dest: "/root/{{ item.dest | basename }}.uncompressed"
      loop: "{{ images }}"
      when: item.src.startswith('http')

    - name: Copy cloud-init image file.
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "/root/{{ item.dest | basename }}.uncompressed"
      loop: "{{ images }}"
      when: not item.src.startswith('http')

    - name: Add 'acl' and 'qemu-guest-agent' to image file and update it.
      ansible.builtin.command: "virt-customize -a {{ item.dest | basename }}.uncompressed --install acl,qemu-guest-agent --update"
      loop: "{{ images }}"

    - name: Sysprep the image file.
      ansible.builtin.command: "virt-sysprep -a {{ item.dest | basename }}.uncompressed --operation defaults,-customize"
      loop: "{{ images }}"

    - name: Compress image file.
      ansible.builtin.command: "virt-sparsify --compress {{ item.dest | basename }}.uncompressed {{ item.dest | basename }}"
      loop: "{{ images }}"

    - name: Download the new image file.
      ansible.builtin.fetch:
        src: "/root/{{ item.dest | basename }}"
        dest: "{{ item.dest }}"
        flat: true
      loop: "{{ images }}"
