---
- name: Create container for 'garage' services.
  gather_facts: false
  hosts: local_garage

  roles:
    - role: cloudcodger.proxmox_client.lxc

- name: >
    Configure 'garage' CT.
    Test Ubuntu roles 'initial_apt_update' and 'netboot_xyz'.
    Install and configure 'apt_cacher'.
  hosts: garage

  roles:
    - role: cloudcodger.ubuntu.initial_apt_update
    - role: cloudcodger.ubuntu.netboot_xyz
    # - role: cloudcodger.ubuntu.apt_mirror
    - role: cloudcodger.ubuntu.nginx

  handlers:
    - name: Reload apt-cacher
      ansible.builtin.service:
        name: apt-cacher
        state: reloaded

  tasks:
    - name: Install 'apt-cacher'.
      ansible.builtin.apt:
        pkg: apt-cacher

    - name: Create a apt-cacher www-data owned directories.
      ansible.builtin.file:
        path: "/apt-cacher"
        state: directory
        owner: www-data
        group: www-data
        mode: "0755"
      notify: Reload apt-cacher

    - name: Insert/Update apt-cacher configuration
      ansible.builtin.blockinfile:
        create: true
        path: /etc/apt-cacher/conf.d/garage
        block: |
          allowed_hosts = *
          cache_dir = /apt-cacher
          distinct_namespaces = 1
          group = www-data
          user = www-data
      notify: Reload apt-cacher

    - name: Create an grafana_alloy/ files for NGINX to server.
      ansible.builtin.copy:
        src: grafana_alloy/
        dest: "{{ nginx_base }}/{{ inventory_hostname }}"
      notify: Reload nginx
