---
- name: Create VMs for a Kubernetes cluster using 'k0s' and installed via Ansible.
  gather_facts: false
  hosts: localhost

  vars_files:
    - custom_vars/k0s.yml

  roles:
    - role: cloudcodger.proxmox_client.cloud_init
