---
- name: Update the local ~/.ssh/known_hosts file with all keys.
  gather_facts: false
  hosts: localhost

  tasks:
    - name: Scan for ssh-hostkeys
      ansible.builtin.command:
        cmd: "/usr/bin/ssh-keyscan {{ item }} {{ hostvars[item]['ansible_host'] }}"
      changed_when: false
      ignore_errors: true
      register: keyscan_cmd
      loop: "{{ query('inventory_hostnames', host_list) if host_list is defined else
        groups[group_name | default('proxmox_all_running')] }}"

    - name: Add hostkeys to known_hosts
      ansible.builtin.lineinfile:
        path: ~/.ssh/known_hosts
        regexp: "^{{ item.split()[:2] | join(' ') }}"
        line: "{{ item }}"
      loop: "{{ keyscan_cmd.results | map(attribute='stdout_lines') | flatten }}"
      loop_control:
        label: "{{ item.split()[:2] | join(' ') }}"
      when: item[:1] != '#'
