---
- name: Create VMs for MinIO.
  gather_facts: false
  hosts: localhost

  vars:
    cloud_init_work_cores: 2
    cloud_init_work_memory: '4096'
    cloud_init_work_tags: [minio]
    cloud_init_image: ubuntu-24.04-qemu-guest.qcow2
    cloud_init_startup_pause: 1
    cloud_init_vms:
      - name: minio1
        control: false
        ip: "192.168.6.246/24"
        pm_host: gadget1
        vmid: "6246"
      - name: minio2
        control: false
        ip: "192.168.6.247/24"
        pm_host: gadget2
        vmid: "6247"
      - name: minio3
        control: false
        ip: "192.168.6.248/24"
        pm_host: gadget3
        vmid: "6248"

  roles:
    - role: cloudcodger.proxmox_client.cloud_init

  tasks:
    - name: Create second disks for the Virtual Machines
      community.general.proxmox_disk:
        api_host: "{{ cloud_init_pm_api_host }}"
        api_user: "{{ cloud_init_pm_api_user }}"
        api_token_id: ansible
        api_token_secret: "{{ lookup('file', '~/.pve_tokens/lab-s1m0ne-pve-ansible.token') }}"

        disk: "scsi1"
        size: '120'
        storage: local-lvm
        vmid: "{{ item }}"
      loop: 
        - "6246"
        - "6247"
        - "6248"
