---
- name: Stop and Remove Containers and VMs to clean up after testing.
  gather_facts: false
  hosts: localhost

  vars_files:
    - custom_vars/name_server.yml

  # roles:
  #   - role: destroyer
  #     destroyer_group: name_server
  #   - role: destroyer
  #     destroyer_group: ns_single
  #   - role: destroyer
  #     destroyer_group: ns_split
  #   - role: destroyer
  #     destroyer_group: ns_vm

  # Using the 'include_role' instead of above in order to avoid
  # warnings and errors for groups that do not exist in the cluster.
  tasks:
    - name: Pass variables to role
      ansible.builtin.include_role:
        name: destroyer
      vars:
        destroyer_group: "{{ grp }}"
      loop:
        - name_server
        - ns_single
        - ns_split
        - ns_vm
      loop_control:
        loop_var: grp
      when: "groups[grp] is defined"
