---
collections:
  - name: cloudcodger.dns
    version: "2.0.1"
  - name: cloudcodger.k8s
    version: "3.0.0"
  - name: cloudcodger.proxmox_client
    version: "2.0.2"
  - name: cloudcodger.proxmox_openssh
    version: "1.3.1"
  - name: cloudcodger.ubuntu
    version: "2.0.0"
  - name: grafana.grafana
    version: "5.7.0"
