---
- name: Stop and Remove 'study' VM to clean up after testing.
  gather_facts: false
  hosts: localhost

  roles:
    - role: destroyer
      destroyer_group: study_ct
    - role: destroyer
      destroyer_group: study_vm
