---
- name: Create container for 'study' machine.
  gather_facts: false
  hosts: localhost

  vars:
    lxc_cores: 2
    lxc_disk_size: "20"
    lxc_memory: "4096"
    lxc_pm_host: gadget3

    # Notice that the tag is different from the container name
    # Ansible will give a warning if you have groups that are the same name as any hosts
    # and you may have unpredictable results when referencing them.
    lxc_tags: ["study_ct"]
    lxc_template: debian-12-standard_12.2-1_amd64.tar.zst

    lxc_cts:
      - name: study
        ip: "192.168.6.5/24"
        vmid: "6005"

  roles:
    - role: cloudcodger.proxmox_client.lxc
