---
replicas: 1

## Create HorizontalPodAutoscaler object for deployment type
#
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 6
  targetCPU: "60"
  targetMemory: ""
  behavior: {}

service:
  enabled: true
  type: LoadBalancer
  loadBalancerIP: "192.168.6.177"

# ingress:
#   enabled: true
#   # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
#   # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
#   ingressClassName: nginx
#   # annotations: {}
#     # kubernetes.io/ingress.class: nginx
#     # kubernetes.io/tls-acme: "true"

#   path: /

#   # pathType is only for k8s >= 1.1=
#   pathType: Prefix
#   hosts:
#     - host: mimir.lab.{{ showcase_base_domain }}

persistence:
  enabled: true
