---
ansible_connection: local

# The cloud_init_* variables are used by the cloudcodger.proxmox_client.cloud_init role
cloud_init_pm_api_host: "192.168.6.251"
cloud_init_pm_api_user: "s1m0ne@pve"
cloud_init_pm_api_token_file: lab-s1m0ne-pve-ansible.token

cloud_init_construct_hosts: [ gadget1, gadget2, gadget3 ]
cloud_init_network_gw: 192.168.6.1
# cloud_init_network_gw6: "2607:fa18:d7fe:ff00::1"
cloud_init_pm_host: gadget1

# Take note that this is a multiline text string and not a list
cloud_init_sshkeys: |
  ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJwg1ybdTSPF2xFm+TS3bjelKO7VQgGpbyvr+b9qJBzr cloudcodger@showcase
  {{ lookup('file', lookup('env', 'HOME') + '/.ssh/showcase.pub') }}
cloud_init_storage: local-lvm

# The lxc_* variables are used by the cloudcodger.proxmox_client.lxc role
lxc_nameservers: ["172.20.1.209", "172.20.1.210"]
lxc_network_gw: 192.168.6.1

lxc_pm_api_host: gadget1
lxc_pm_api_user: "s1m0ne@pve"
lxc_pm_api_token_file: lab-s1m0ne-pve-ansible.token
lxc_pm_host: gadget1

lxc_searchdomains: ["lab.{{ showcase_base_domain }}", "{{ showcase_base_domain }}"]

# Take note that this is a multiline text string and not a list
lxc_sshkeys: "{{ cloud_init_sshkeys }}"
lxc_storage: local-lvm
