---
# This showcases how to use the `host_vars` to make this the Primary Name Server.

bind9_servers_zones:
  - name: "lab.{{ showcase_base_domain }}"
    ns:
      - ns2
      - ns3
    records_var: zone_lab # Set in the `zone_vars/lab.yml` file

  - name: '6.168.192.in-addr.arpa'
    ns:
      - "ns2.{{ showcase_base_domain }}."
      - "ns3.{{ showcase_base_domain }}."
    records_var: zone_192_168_6 # Set in the `zone_vars/192.168.6.yml` file
