---
ansible_user: root

alloy_config: |
  loki.source.file "logfiles" {
    targets    = [
        {"__path__" = "/var/log/auth.log"},
        {"__path__" = "/var/log/syslog"},
      ]
    forward_to = [loki.write.local.receiver]
  }

  loki.write "local" {
    endpoint {
      url = "http://rotary:3100/loki/api/v1/push"
    }
  }

  loki.relabel "journal" {
    forward_to = []

    rule {
      source_labels = ["__journal__systemd_unit"]
      target_label  = "unit"
    }
  }

  loki.source.journal "read"  {
    forward_to    = [loki.write.local.receiver]
    relabel_rules = loki.relabel.journal.rules
    labels        = {component = "loki.source.journal"}
  }

grafana_ini:
  security:
    admin_user: admin
    admin_password: just2showcase1example
