---
alloy_env_file_vars:
  CUSTOM_ARGS: '"--server.http.listen-addr=0.0.0.0:12345"'
  LOKI_URL: http://loki/loki/api/v1/push
  MIMIR_URL: http://mimir/api/v1/push

alloy_config: |
  import.http "showcase_loki" {
    url            = "http://garage/journal.alloy"
    poll_frequency = "15m"
  }

  showcase_loki.journal_monitor "proxmox" {
    environment = "example"
  }

  import.http "showcase_pve" {
    url            = "http://garage/pve.alloy"
    poll_frequency = "15m"
  }

  showcase_pve.pve_monitor "proxmox" {
    environment = "example"
  }

k0s_worker_profiles:
  - name: default
    values:
      maxPods: 220

showcase_base_domain: "{{ lookup('ansible.builtin.env', 'SHOWCASE_BASE_DOMAIN', default='example.com') }}"
