---
ansible_user: ubuntu

alloy_prometheus_minio_enabled: true

minio_browser_redirect_url: http://minio/minio/ui/
minio_data_drive: /dev/sdb
minio_root_password: "{{ lookup('file', '~/.secrets/minio/root_password') }}"
minio_volume_hosts: "minio{1...3}.lab.{{ showcase_base_domain }}"
