---
bind9_servers_zone_default_ttl: 90

bind9_servers_group: ns_single
bind9_servers_zones:
  - name: "lab.{{ showcase_base_domain }}"
    records_var: zone_lab # Set in the `zone_vars/lab.yml` file
  - name: "6.168.192.in-addr.arpa"
    records_var: zone_192_168_6 # Set in the `zone_vars/192.168.6.yml` file

zone_lab:
  - ctrl1;;A;192.168.6.21
  - ctrl2;;A;192.168.6.22
  - ctrl3;;A;192.168.6.23
  - ns0;;A;192.168.6.99
  - ns2;;A;192.168.6.2
  - ns3;;A;192.168.6.3
  - pve1;;A;192.168.6.251
  - pve2;;A;192.168.6.252
  - pve3;;A;192.168.6.253
  - pxe;;A;192.168.6.9
  - router;;A;192.168.6.1
  - work1;;A;192.168.6.24
  - work2;;A;192.168.6.25
  - work3;;A;192.168.6.26
  - zabbix;;A;192.168.6.8

zone_192_168_6:
  - 1;;PTR;router.{{ showcase_base_domain }}.
  - 2;;PTR;ns2.{{ showcase_base_domain }}.
  - 3;;PTR;ns3.{{ showcase_base_domain }}.
  - 8;;PTR;zabbix.{{ showcase_base_domain }}.
  - 9;;PTR;pxe.{{ showcase_base_domain }}.
  - 21;;PTR;ctrl1.{{ showcase_base_domain }}.
  - 22;;PTR;ctrl2.{{ showcase_base_domain }}.
  - 23;;PTR;ctrl3.{{ showcase_base_domain }}.
  - 24;;PTR;work1.{{ showcase_base_domain }}.
  - 25;;PTR;work2.{{ showcase_base_domain }}.
  - 26;;PTR;work3.{{ showcase_base_domain }}.
  - 99;;PTR;ns0.{{ showcase_base_domain }}.
  - 251;;PTR;pve1.{{ showcase_base_domain }}.
  - 252;;PTR;pve2.{{ showcase_base_domain }}.
  - 253;;PTR;pve3.{{ showcase_base_domain }}.
